export const destinations = [
  { value: "DEL", label: "New Delhi (DEL)" },
  { value: "BOM", label: "Mumbai (BOM)" },
  { value: "BLR", label: "Bengaluru (BLR)" },
  { value: "MAA", label: "Chennai (MAA)" },
  { value: "CCU", label: "Kolkata (CCU)" },
  { value: "HYD", label: "Hyderabad (HYD)" },
  { value: "PNQ", label: "Pune (PNQ)" },
  { value: "AMD", label: "Ahmedabad (AMD)" },
  { value: "GOI", label: "Goa (GOI)" },
  { value: "COK", label: "Kochi (COK)" },
];

// Dummy flights that would be fetched from an API in a real app
export const availableFlights = [
  {
    id: "SR101",
    departure: "08:00",
    arrival: "10:05",
    duration: "2h 5m",
    price: 5400,
  },
  {
    id: "SR102",
    departure: "12:30",
    arrival: "14:45",
    duration: "2h 15m",
    price: 6200,
  },
  {
    id: "SR103",
    departure: "18:45",
    arrival: "21:00",
    duration: "2h 15m",
    price: 4800,
  },
];

export const allFlights = [
  {
    id: "SR101",
    from: "New Delhi (DEL)",
    to: "Mumbai (BOM)",
    departure: "08:00",
    arrival: "10:05",
    status: "On Time",
  },
  {
    id: "SR202",
    from: "Mumbai (BOM)",
    to: "Bengaluru (BLR)",
    departure: "11:30",
    arrival: "13:00",
    status: "Delayed",
  },
  {
    id: "SR303",
    from: "Bengaluru (BLR)",
    to: "Chennai (MAA)",
    departure: "14:15",
    arrival: "15:10",
    status: "On Time",
  },
  {
    id: "SR404",
    from: "Chennai (MAA)",
    to: "Kolkata (CCU)",
    departure: "09:45",
    arrival: "12:00",
    status: "Cancelled",
  },
  {
    id: "SR505",
    from: "Kolkata (CCU)",
    to: "Hyderabad (HYD)",
    departure: "18:00",
    arrival: "20:10",
    status: "On Time",
  },
  {
    id: "SR606",
    from: "Hyderabad (HYD)",
    to: "Pune (PNQ)",
    departure: "06:20",
    arrival: "07:30",
    status: "On Time",
  },
  {
    id: "SR707",
    from: "Pune (PNQ)",
    to: "Ahmedabad (AMD)",
    departure: "20:00",
    arrival: "21:15",
    status: "Delayed",
  },
  {
    id: "SR808",
    from: "Ahmedabad (AMD)",
    to: "Goa (GOI)",
    departure: "12:30",
    arrival: "14:00",
    status: "On Time",
  },
  {
    id: "SR909",
    from: "Goa (GOI)",
    to: "Kochi (COK)",
    departure: "16:00",
    arrival: "17:30",
    status: "On Time",
  },
  {
    id: "SR110",
    from: "Kochi (COK)",
    to: "New Delhi (DEL)",
    departure: "19:00",
    arrival: "22:00",
    status: "On Time",
  },
];
